/usr/bin/ruby1.9.1 extconf.rb 
creating Makefile
Compiling v8 for ia32
Using python 2.7.3
Using compiler: /usr/bin/c++ (GCC version 4.7)
/bin/sh: 1: build/gyp/gyp: Permission denied
make: *** [out/Makefile.ia32] Error 126
/media/Data/second_sem/cloud/projects/first-app/vendor/bundle/ruby/1.9.1/gems/libv8-3.16.14.7/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/media/Data/second_sem/cloud/projects/first-app/vendor/bundle/ruby/1.9.1/gems/libv8-3.16.14.7/vendor/v8/out/ia32.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /media/Data/second_sem/cloud/projects/first-app/vendor/bundle/ruby/1.9.1/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `each'
	from /media/Data/second_sem/cloud/projects/first-app/vendor/bundle/ruby/1.9.1/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `verify_installation!'
	from /media/Data/second_sem/cloud/projects/first-app/vendor/bundle/ruby/1.9.1/gems/libv8-3.16.14.7/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=ia32 \
	              -S.ia32  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
